name: thesis
channels:
  - defaults
dependencies:
    - python=3.10
    - pip:
        - matplotlib=3.10.7
        - numpy=2.3.4
        - pandas=2.3.3
        - praat-parselmouth=0.4.6
        - sounddevice=0.5.3
        - keyboard=0.13.5